[package]
name = "shine-identity"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
thiserror = "1.0"
anyhow = "1.0"
config = "0.13"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "2.3"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.3", features = ["v4", "serde"] }
base64 = "0.21"
futures = "0.3"
tokio = {version = "1.27", features = ["macros", "rt-multi-thread", "signal"] }

oauth2 = "4.3"
openidconnect = "3.0"

bb8 = "0.8"
bb8-postgres = "0.8"
tokio-postgres = { version = "0.7", features = ["with-uuid-1", "with-chrono-0_4", "runtime"] }
tokio-rustls = "0.24"
tokio-postgres-rustls = "0.10"
refinery = { version = "0.8", features = ["tokio-postgres"] }

azure_core = { version = "0.11" }
azure_identity = { version = "0.11" }

tera = "1.18"

tracing = "0.1"
tracing-log = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tower-http = { version = "0.4", features = ["cors"] }
axum = "0.6"
#axum-server = { version = "0.4", features = ["tls-rustls"] }
axum-extra = { version = "0.7", features = ["cookie", "cookie-signed", "cookie-private"] }

shine-service = { path = "./shine-service-rs/shine-service", version = "0.1.0" }
